options:
  logging: NONE  # No envía logs a Cloud Logging ni crea bucket

timeout: '1200s'

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pl-nodriver', '.']

  # Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pl-nodriver']

  # Deploy to Cloud Run in multiple regions in parallel
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        REGIONS=(
          "us-central1"
          "us-east1"
          "us-east4"
          "us-east5"
          "us-west1"
          "us-west2"
          "us-west3"
          "us-west4"
          "us-south1"
        )

        for REGION in "${REGIONS[@]}"; do
          gcloud run deploy pl-nodriver \
            --image gcr.io/$PROJECT_ID/pl-nodriver \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --port 80 \
            --concurrency 1 \
            --memory 1Gi \
            --cpu 1 \
            --quiet &
        done

        wait
