options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/${PROJECT_ID}/pl-nodriver
      - .

  # 2. Subir la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/${PROJECT_ID}/pl-nodriver

  # 3. Desplegar en múltiples regiones
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        REGIONS=("us-central1" "us-east1" "us-west1" "us-east4")
        for REGION in "${REGIONS[@]}"; do
          echo "Desplegando en $REGION..."
          gcloud run deploy pl-nodriver \
            --image gcr.io/${PROJECT_ID}/pl-nodriver \
            --region "$REGION" \
            --platform managed \
            --port 80 \
            --memory 2Gi \
            --cpu 2 \
            --concurrency 1 \
            --quiet || exit 1

          echo "Haciendo público el servicio en $REGION..."
          gcloud run services add-iam-policy-binding pl-nodriver \
            --region="$REGION" \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --quiet || exit 1
        done
