options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/pl-nodriver
      - .

  # 2. Subir la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/pl-nodriver

  # 3. Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - pl-nodriver
      - --image
      - gcr.io/$PROJECT_ID/pl-nodriver
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "80"
      - "--memory"
      - "2Gi"
      - "--cpu"
      - "2"
